site_name: Control-M SELab
site_description: Project documentation for the Control-M SELab
site_author: SELab Team

repo_name: SELab Docs
repo_url: http://vl-cpo01.ctm.bmc.com/cpolansk/selab-docs
edit_uri: ""
copyright: >
  Helps us keep these
  <b><a href="http://vl-cpo01.ctm.bmc.com/cpolansk/selab-docs">docs</a></b>
  up-to-date, and complete! 

use_directory_urls: true

theme:
  name: 'material'
  logo: 'images/logo.svg'
  language: 'en'
  palette:
    primary: 'deep orange'
    accent: 'orange'
  feature:
    tabs: true

nav:
  - Home: index.md
  - Help: help.md
  - Contributing: contributing.md
  - License: license.md
  - SELab:
    - Overview: selab/index.md
    - Where Do I Start?: selab/connect.md
    - Legacy Systems: selab/legacy.md
